; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{4F1B81E8-42E9-4958-91B7-2A87703DD078}
AppName=UCPS CD
AppVerName=UCPS CD 0.9
AppPublisher=Unie èeských pìveckých sborù
AppPublisherURL=http://www.ucps.cz/
AppSupportURL=http://www.ucps.cz/
AppUpdatesURL=http://www.ucps.cz/
DefaultDirName={pf}\UCPS CD
DefaultGroupName=UCPS CD
AllowNoIcons=yes
OutputBaseFilename=setup
Compression=lzma
SolidCompression=yes

[Languages]
Name: "czech"; MessagesFile: "compiler:Languages\Czech.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\dev\python\ucpscd\dist\ucpscd.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dev\python\ucpscd\dist\icon.gif"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dev\python\ucpscd\dist\logo.gif"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dev\python\ucpscd\dist\MSVCR71.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dev\python\ucpscd\dist\python25.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dev\python\ucpscd\dist\runtime.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dev\python\ucpscd\dist\ucps.db"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dev\python\ucpscd\dist\w9xpopen.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dev\python\ucpscd\dist\images\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

;Source: "C:\WINDOWS\system32\OLEAUT32.dll"; DestDir: "{sys}"; Flags: onlyifdoesntexist uninsneveruninstall
;Source: "C:\WINDOWS\system32\USER32.dll";  DestDir: "{sys}"; Flags: onlyifdoesntexist uninsneveruninstall
;Source: "C:\WINDOWS\system32\COMCTL32.dll"; DestDir: "{sys}"; Flags: onlyifdoesntexist uninsneveruninstall
;Source: "C:\WINDOWS\system32\SHELL32.dll"; DestDir: "{sys}"; Flags: onlyifdoesntexist uninsneveruninstall
;Source: "C:\WINDOWS\system32\ole32.dll"; DestDir: "{sys}"; Flags: onlyifdoesntexist uninsneveruninstall
;Source: "C:\WINDOWS\system32\WINMM.dll"; DestDir: "{sys}"; Flags: onlyifdoesntexist uninsneveruninstall
;Source: "C:\WINDOWS\system32\WSOCK32.dll"; DestDir: "{sys}"; Flags: onlyifdoesntexist uninsneveruninstall
;Source: "C:\WINDOWS\system32\comdlg32.dll"; DestDir: "{sys}"; Flags: onlyifdoesntexist uninsneveruninstall
;Source: "C:\WINDOWS\system32\ADVAPI32.dll"; DestDir: "{sys}"; Flags: onlyifdoesntexist uninsneveruninstall
;Source: "C:\WINDOWS\system32\msvcrt.dll"; DestDir: "{sys}"; Flags: onlyifdoesntexist uninsneveruninstall
;Source: "C:\WINDOWS\system32\GDI32.dll"; DestDir: "{sys}"; Flags: onlyifdoesntexist uninsneveruninstall
Source: "c:\Program Files\Python25\wx-2.8-msw-unicode\wx\MSVCP71.dll"; DestDir: "{app}"
;Source: "C:\WINDOWS\system32\KERNEL32.dll"; DestDir: "{sys}"; Flags: onlyifdoesntexist uninsneveruninstall
Source: "c:\Program Files\Python25\wx-2.8-msw-unicode\wx\gdiplus.dll"; DestDir: "{app}"
;Source: "C:\WINDOWS\system32\RPCRT4.dll"; DestDir: "{sys}"; Flags: onlyifdoesntexist uninsneveruninstall



[Icons]
Name: "{group}\UCPS CD"; Filename: "{app}\ucpscd.exe"
Name: "{group}\{cm:ProgramOnTheWeb,UCPS CD}"; Filename: "http://www.ucps.cz/"
Name: "{group}\{cm:UninstallProgram,UCPS CD}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\UCPS CD"; Filename: "{app}\ucpscd.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\ucpscd.exe"; Description: "{cm:LaunchProgram,UCPS CD}"; Flags: nowait postinstall skipifsilent

